"use client";

import { use, useCallback, useEffect, useState } from "react";
import { Activity, ArrowRight, Ban, CheckCircle2, ChevronRight, FlaskConical, LockKeyhole, Radar, ShieldCheck } from "lucide-react";
import { AppShell } from "../../../../components/app-shell";
import { ErrorMessage, Loading } from "../../../../components/status";
import { api } from "../../../../lib/api";

type Stage = { stage: string; outcome: string; detail?: string; durationMs?: number };
type BoundaryScan = { target: string; outcome: string; rawMatchCount: number; canaryMatchCount: number; bytesInspected: number; artifactHash: string; detail: string };
type Receipt = { id: string; traceId: string; operation: string; purpose: string; status: string; stages: Stage[]; entityCounts: Record<string, number>; provider: string; modelProvider?: string | null; providerPayloadHash?: string | null; providerPayloadBytes?: number | null; providerPayloadStatus?: string | null; boundaryScans: BoundaryScan[]; rawLeakCount: number; eventHash: string; createdAt: string };
type Attack = { id: string; scenarioId: string; category: string; outcome: string; boundary: string; traceId: string; createdAt: string };
type Proof = { summary: { totalReceipts: number; blockedOperations: number; leakEvents: number; verifiedStages: number; destinationScans: number }; recent: Receipt[]; attacks: Attack[] };
type Scenario = { id: string; title: string; category: string; boundary: string; description: string };
const pipeline = ["Authorize", "Discover", "Protect", "Guardrail", "Retrieve", "AI / tools", "Leak scan", "Reveal"];

export default function PrivacyProofPage({ params }: { params: Promise<{ patientId: string }> }) {
  const { patientId } = use(params); const [profile, setProfile] = useState<{ displayName: string } | null>(null); const [proof, setProof] = useState<Proof | null>(null); const [scenarios, setScenarios] = useState<Scenario[]>([]); const [running, setRunning] = useState(""); const [selectedTraceId, setSelectedTraceId] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const [p, evidence, attacks] = await Promise.all([api<{ displayName: string }>(`/v1/profiles/${patientId}`), api<Proof>(`/v1/profiles/${patientId}/privacy-proof`), api<Scenario[]>("/v1/privacy/attacks")]); setProfile(p); setProof(evidence); setScenarios(attacks); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load privacy evidence."); } }, [patientId]);
  useEffect(() => { void load(); }, [load]);
  async function run(scenarioId: string) { setRunning(scenarioId); setError(""); try { const result = await api<Attack>(`/v1/profiles/${patientId}/privacy-attacks/run`, { method: "POST", body: JSON.stringify({ scenarioId }) }); setSelectedTraceId(result.traceId); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Attack run failed."); } finally { setRunning(""); } }
  function selectTrace(traceId: string) { setSelectedTraceId(traceId); requestAnimationFrame(() => document.getElementById("selected-trace")?.scrollIntoView({ behavior: "smooth", block: "start" })); }
  if (!profile || !proof) return <AppShell>{error ? <ErrorMessage message={error} /> : <Loading />}</AppShell>;
  const selected = proof.recent.find((receipt) => receipt.traceId === selectedTraceId) ?? proof.recent[0];

  return <AppShell patient={{ id: patientId, preferredName: profile.displayName }} purpose="Privacy evidence">
    <div className="proof-hero"><div><p className="overline light-copy">Live verifiable evidence</p><h1>Privacy Proof</h1><p>See exactly where Protegrity protected data, what the AI received, which policy ran, and whether any raw value crossed a boundary.</p></div><div className="proof-seal"><ShieldCheck /><strong>{proof.summary.leakEvents === 0 ? "No raw leaks detected" : "Leak event requires review"}</strong><span>Across recorded protected operations</span></div></div>
    {error && <ErrorMessage message={error} />}
    <section className="pipeline-panel" aria-label="Protected AI pipeline">{pipeline.map((step, index) => <div key={step} className="pipeline-step"><span><CheckCircle2 /></span><strong>{step}</strong><small>{index === 0 ? "purpose + scope" : index === 1 ? "Protegrity entities" : index === 2 ? "pseudonymize" : index === 5 ? "minimum necessary" : "verified"}</small>{index < pipeline.length - 1 && <ArrowRight className="pipeline-arrow" />}</div>)}</section>
    <div className="proof-metrics"><div><Activity /><strong>{proof.summary.totalReceipts ?? 0}</strong><span>Protection receipts</span></div><div><Ban /><strong>{proof.summary.blockedOperations ?? 0}</strong><span>Blocked operations</span></div><div><Radar /><strong>{proof.summary.destinationScans ?? 0}</strong><span>Destination scans</span></div><div className={(proof.summary.leakEvents ?? 0) > 0 ? "danger" : "safe"}><LockKeyhole /><strong>{proof.summary.leakEvents ?? 0}</strong><span>Released raw leaks</span></div></div>

    <section className="panel receipt-explorer"><div className="panel-title"><div><p className="overline">Complete operation history</p><h2>Protection receipts</h2></div><span className="count-badge">{proof.recent.length} shown</span></div><div className="receipt-list">{proof.recent.map((receipt) => <button key={receipt.id} className={selected?.id === receipt.id ? "selected" : ""} onClick={() => selectTrace(receipt.traceId)}><span><strong>{receipt.operation.replaceAll("_", " ")}</strong><small>{new Date(receipt.createdAt).toLocaleString()} · {receipt.purpose.replaceAll("_", " ")}</small></span><span className={`status ${receipt.status === "blocked" || receipt.status === "failed" ? "failed" : "verified"}`}>{receipt.status}</span><ChevronRight /></button>)}</div></section>

    {selected && <section className="panel trace-detail" id="selected-trace"><div className="panel-title"><div><p className="overline">Selected trace</p><h2>{selected.operation}</h2></div><span className={`status ${selected.status === "blocked" || selected.status === "failed" ? "failed" : "verified"}`}>{selected.status}</span></div><div className="trace-meta"><span>Trace <code>{selected.traceId}</code></span><span>Purpose <strong>{selected.purpose.replaceAll("_", " ")}</strong></span><span>Protection provider <strong>{selected.provider}</strong></span><span>Model provider <strong>{selected.modelProvider ?? "not called"}</strong></span><span>Provider payload <strong>{selected.providerPayloadStatus ?? "not called"}</strong></span><span>Released leak count <strong>{selected.rawLeakCount}</strong></span></div>{selected.providerPayloadHash && <div className="hash-chain"><ShieldCheck /><span>Exact provider request · {selected.providerPayloadBytes ?? 0} bytes</span><code>{selected.providerPayloadHash}</code></div>}<div className="entity-summary"><strong>Discovered entity counts</strong><div className="token-row">{Object.entries(selected.entityCounts).length ? Object.entries(selected.entityCounts).map(([entity, count]) => <span key={entity}>{entity}: {count}</span>) : <span>No raw identifiers detected</span>}</div></div><div className="stage-list">{selected.stages.map((stage, index) => <div key={`${stage.stage}-${index}`}><CheckCircle2 /><span><strong>{stage.stage.replaceAll("_", " ")}</strong><small>{stage.detail || stage.outcome}{stage.durationMs ? ` · ${stage.durationMs} ms` : ""}</small></span></div>)}</div>{selected.boundaryScans?.length > 0 && <div className="boundary-scan-list"><strong>Destination inspection evidence</strong>{selected.boundaryScans.map((scan, index) => <article key={`${scan.target}-${index}`}><div><ShieldCheck /><span><strong>{scan.target.replaceAll("_", " ")}</strong><small>{scan.detail}</small></span><span className={`status ${scan.outcome === "failed" ? "failed" : "verified"}`}>{scan.outcome}</span></div><p>{scan.bytesInspected.toLocaleString()} bytes · raw matches {scan.rawMatchCount} · canary matches {scan.canaryMatchCount}</p><code>{scan.artifactHash}</code></article>)}</div>}<div className="hash-chain"><LockKeyhole /><span>Hash-chained receipt</span><code>{selected.eventHash}</code></div></section>}

    <section className="attack-lab"><div className="page-heading"><div><p className="overline">Adversarial verification</p><h2>Attack Lab</h2><p>Run realistic privacy attacks and open the exact receipt for the boundary that blocked each one.</p></div><FlaskConical /></div><div className="attack-grid">{scenarios.map((scenario) => { const result = proof.attacks.find((item) => item.scenarioId === scenario.id); return <article key={scenario.id}><div><span className="scenario-id">{scenario.id}</span>{result && <span className={`status ${result.outcome === "blocked" ? "verified" : "failed"}`}>{result.outcome}</span>}</div><h3>{scenario.title}</h3><p>{scenario.description}</p><small>Expected boundary: {scenario.boundary}</small><button className="secondary-button compact" disabled={running === scenario.id} onClick={() => void run(scenario.id)}>{running === scenario.id ? "Running…" : "Run attack"}</button>{result && <button className="attack-result" onClick={() => selectTrace(result.traceId)}><ShieldCheck />Blocked at {result.boundary}<code>{result.traceId}</code><ChevronRight /></button>}</article>; })}</div></section>
  </AppShell>;
}
