"use client";

import { FormEvent, use, useCallback, useEffect, useState } from "react";
import { CalendarCheck2, CheckCircle2, Clock3, Plus, ShieldCheck, X } from "lucide-react";
import { AppShell } from "../../../../components/app-shell";
import { ErrorMessage, Loading } from "../../../../components/status";
import { api } from "../../../../lib/api";

type Data = { patient: { id: string; preferredName: string; role?: string }; tasks: Array<{ id: string; title: string; dueAt?: string; reminderAt?: string; status: string }>; appointments: Array<{ id: string; startsAt: string; providerName?: string; reason?: string; status: string }> };

export default function FollowUpsPage({ params }: { params: Promise<{ patientId: string }> }) {
  const { patientId } = use(params); const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [adding, setAdding] = useState(false);
  const load = useCallback(async () => { try { setData(await api<Data>(`/v1/patients/${patientId}/dashboard?purpose=appointment_preparation`)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load follow-ups."); } }, [patientId]);
  useEffect(() => { void load(); }, [load]);
  async function complete(id: string) { try { await api(`/v1/patients/${patientId}/tasks/${id}/complete?purpose=appointment_preparation`, { method: "POST" }); setNotice("Follow-up confirmed complete and preserved in audit history."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not complete the follow-up."); } }
  async function addAppointment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api(`/v1/patients/${patientId}/appointments`, { method: "POST", body: JSON.stringify({ startsAt: new Date(String(form.get("startsAt"))).toISOString(), providerName: form.get("providerName") || undefined, location: form.get("location") || undefined, reason: form.get("reason") || undefined }) }); setAdding(false); setNotice("Appointment protected and added to follow-up preparation."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not add the appointment."); } }
  if (!data) return <AppShell>{error ? <ErrorMessage message={error} /> : <Loading />}</AppShell>;
  const overdue = data.tasks.filter((task) => task.dueAt && new Date(task.dueAt) < new Date());
  return <AppShell patient={data.patient} purpose="Appointment preparation"><div className="page-heading"><div><p className="overline">No follow-up left behind</p><h1>Follow-ups</h1><p>Source-linked actions from records, discharge instructions, and appointments—without turning suggestions into clinical facts.</p></div><button className="primary-button compact" onClick={() => setAdding(true)}><Plus size={16} />Add appointment</button></div>
    {error && <ErrorMessage message={error} />}{notice && <div className="message success" role="status">{notice}</div>}
    <div className="metric-strip"><div><strong>{data.tasks.length}</strong><span>Open actions</span></div><div className={overdue.length ? "alert" : ""}><strong>{overdue.length}</strong><span>Overdue</span></div><div><strong>{data.appointments.length}</strong><span>Upcoming visits</span></div></div>
    <div className="dashboard-grid"><section className="panel"><div className="panel-title"><div><p className="overline">Action queue</p><h2>What comes next</h2></div><CheckCircle2 /></div><div className="intelligence-list">{data.tasks.length ? data.tasks.map((task) => <article key={task.id}><div><strong>{task.title}</strong><span><Clock3 size={13} /> {task.dueAt ? new Date(task.dueAt).toLocaleString() : "No deadline"}</span></div><div className="row-actions">{task.dueAt && new Date(task.dueAt) < new Date() ? <span className="status failed">overdue</span> : <span className="status active">open</span>}<button className="secondary-button compact" onClick={() => void complete(task.id)}><CheckCircle2 size={15} />Confirm done</button></div></article>) : <p className="muted">No open follow-ups.</p>}</div></section>
    <section className="panel"><div className="panel-title"><div><p className="overline">Preparation</p><h2>Upcoming appointments</h2></div><CalendarCheck2 /></div><div className="intelligence-list">{data.appointments.length ? data.appointments.map((visit) => <article key={visit.id}><div><strong>{visit.providerName || "Scheduled appointment"}</strong><span>{new Date(visit.startsAt).toLocaleString()} · {visit.reason || "Reason protected"}</span></div></article>) : <p className="muted">No upcoming appointments.</p>}</div></section></div>
    {adding && <div className="dialog-backdrop" onMouseDown={() => setAdding(false)}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="appointment-title" onMouseDown={(event) => event.stopPropagation()}><button className="dialog-close icon-button" aria-label="Close" onClick={() => setAdding(false)}><X /></button><p className="overline">Appointment preparation</p><h2 id="appointment-title">Add an appointment</h2><form className="stack" onSubmit={addAppointment}><label>Date and time<input type="datetime-local" name="startsAt" required autoFocus /></label><label>Provider<input name="providerName" /></label><label>Location<input name="location" /></label><label>Reason<textarea name="reason" rows={3} /></label><button className="primary-button"><ShieldCheck size={16} />Protect and add appointment</button></form></section></div>}
  </AppShell>;
}
