"use client";
import { FormEvent, use, useEffect, useState } from "react";
import { Filter, Plus } from "lucide-react";
import { AppShell } from "../../../../components/app-shell";
import { ErrorMessage, Loading } from "../../../../components/status";
import { api } from "../../../../lib/api";

type Event = { id: string; occurredAt: string; category: string; summary: string; source: string };
export default function TimelinePage({ params }: { params: Promise<{ patientId: string }> }) {
  const { patientId } = use(params); const [patient, setPatient] = useState<{ id: string; preferredName: string } | null>(null); const [events, setEvents] = useState<Event[] | null>(null); const [category, setCategory] = useState(""); const [adding, setAdding] = useState(false); const [error, setError] = useState("");
  async function load() { const dashboard = await api<{ patient: { id: string; preferredName: string } }>(`/v1/patients/${patientId}/dashboard`); setPatient(dashboard.patient); setEvents(await api(`/v1/patients/${patientId}/timeline${category ? `?category=${category}` : ""}`)); }
  useEffect(() => { load().catch((e) => setError(e instanceof Error ? e.message : "Could not load timeline.")); }, [patientId, category]);
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await api(`/v1/patients/${patientId}/timeline`, { method: "POST", body: JSON.stringify({ category: form.get("category"), summary: form.get("summary"), occurredAt: new Date(String(form.get("occurredAt"))).toISOString(), source: "caregiver" }) }); setAdding(false); await load(); }
  return <AppShell patient={patient ?? undefined}><div className="page-heading"><div><p className="overline">Longitudinal record</p><h1>{patient?.preferredName ?? "Care"} timeline</h1><p>Observations stay traceable to their author and source.</p></div><button className="primary-button compact" onClick={() => setAdding(true)}><Plus size={18} />Add care note</button></div>
    <div className="filter-bar"><Filter size={17} /><label htmlFor="category-filter">Show</label><select id="category-filter" value={category} onChange={(e) => setCategory(e.target.value)}><option value="">All care events</option>{["symptom","meal","hydration","sleep","mood","fall","note","medication","appointment","care_plan","emergency"].map((value) => <option key={value} value={value}>{value.replace("_", " ")}</option>)}</select></div>
    {error && <ErrorMessage message={error} />}{events === null ? <Loading /> : <section className="full-timeline">{events.map((item) => <article key={item.id}><div className="timeline-date"><strong>{new Date(item.occurredAt).getDate()}</strong><span>{new Intl.DateTimeFormat("en", { month: "short" }).format(new Date(item.occurredAt))}</span></div><span className={`event-mark ${item.category}`} /><div><p className="role-pill">{item.category.replace("_", " ")}</p><h2>{item.summary}</h2><small>{new Intl.DateTimeFormat("en", { hour: "numeric", minute: "2-digit" }).format(new Date(item.occurredAt))} · Source: {item.source}</small></div></article>)}</section>}
    {adding && <div className="dialog-backdrop" onMouseDown={() => setAdding(false)}><section className="dialog" role="dialog" aria-modal="true" onMouseDown={(e) => e.stopPropagation()}><p className="overline">Care observation</p><h2>Add to the timeline</h2><form className="stack" onSubmit={add}><label>What happened?<textarea name="summary" required rows={4} autoFocus /></label><div className="form-row"><label>Type<select name="category" defaultValue="note">{["symptom","meal","hydration","sleep","mood","fall","note","medication","appointment","care_plan","emergency"].map((value) => <option key={value} value={value}>{value.replace("_", " ")}</option>)}</select></label><label>When?<input type="datetime-local" name="occurredAt" required defaultValue={new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0,16)} /></label></div><div className="dialog-actions"><button type="button" className="text-button" onClick={() => setAdding(false)}>Cancel</button><button className="primary-button compact">Save observation</button></div></form></section></div>}
  </AppShell>;
}
